import type { Stock } from "./types";

export const INITIAL_STOCKS: Stock[] = [
  {
    id: "1",
    name: "Franco-Nevada Corp",
    symbol: "FNV.TO",
    currency: "CAD",
    sector: "Materials",
    executedPrice: 303.09,
    cadPriceAtExecution: 303.1,
    shares: 1.0,
    bookValue: 303.1,
  },
  {
    id: "2",
    name: "Agnico Eagle Mines",
    symbol: "AEM.TO",
    currency: "CAD",
    sector: "Materials",
    executedPrice: 232.22,
    cadPriceAtExecution: 232.2,
    shares: 2.0,
    bookValue: 464.4,
  },
  {
    id: "3",
    name: "Atkinsrealis Group Inc",
    symbol: "ATRL.TO",
    currency: "CAD",
    sector: "Industrials",
    executedPrice: 100.03,
    cadPriceAtExecution: 100.0,
    shares: 6.0,
    bookValue: 600.2,
  },
  {
    id: "4",
    name: "Bombardier Inc. Cl B",
    symbol: "BBD-B.TO",
    currency: "CAD",
    sector: "Industrials",
    executedPrice: 189.78,
    cadPriceAtExecution: 189.8,
    shares: 1.0,
    bookValue: 189.8,
  },
  {
    id: "5",
    name: "Element Fleet Mgmt",
    symbol: "EFN.TO",
    currency: "CAD",
    sector: "Industrials",
    executedPrice: 36.37,
    cadPriceAtExecution: 36.4,
    shares: 20.0,
    bookValue: 727.4,
  },
  {
    id: "6",
    name: "WSP Global Inc",
    symbol: "WSP.TO",
    currency: "CAD",
    sector: "Industrials",
    executedPrice: 272.0,
    cadPriceAtExecution: 272.0,
    shares: 2.0,
    bookValue: 544.0,
  },
  {
    id: "7",
    name: "Micron Technology",
    symbol: "MU",
    currency: "USD",
    sector: "Info Tech",
    executedPrice: 199.05,
    cadPriceAtExecution: 277.0,
    shares: 1.0,
    bookValue: 277.0,
  },
  {
    id: "8",
    name: "Dollarama Inc.",
    symbol: "DOL.TO",
    currency: "CAD",
    sector: "Consumer",
    executedPrice: 183.52,
    cadPriceAtExecution: 183.5,
    shares: 3.0,
    bookValue: 550.6,
  },
  {
    id: "9",
    name: "Aritzia Inc.",
    symbol: "ATZ.TO",
    currency: "CAD",
    sector: "Consumer",
    executedPrice: 82.88,
    cadPriceAtExecution: 82.9,
    shares: 5.0,
    bookValue: 414.4,
  },
  {
    id: "10",
    name: "Loblaw Companies",
    symbol: "L.TO",
    currency: "CAD",
    sector: "Consumer",
    executedPrice: 53.8,
    cadPriceAtExecution: 53.81,
    shares: 11.0,
    bookValue: 591.8,
  },
  {
    id: "11",
    name: "Boston Scientific Co",
    symbol: "BSX",
    currency: "USD",
    sector: "Health Care",
    executedPrice: 99.34,
    cadPriceAtExecution: 138.2,
    shares: 7.0,
    bookValue: 967.6,
  },
  {
    id: "12",
    name: "TMX Group Ltd.",
    symbol: "X.TO",
    currency: "CAD",
    sector: "Financials",
    executedPrice: 52.31,
    cadPriceAtExecution: 52.31,
    shares: 11.0,
    bookValue: 575.5,
  },
  {
    id: "13",
    name: "Mastercard Inc",
    symbol: "MA",
    currency: "USD",
    sector: "Financials",
    executedPrice: 583.59,
    cadPriceAtExecution: 812.0,
    shares: 1.0,
    bookValue: 812.0,
  },
  {
    id: "14",
    name: "Brookfield Corp",
    symbol: "BN.TO",
    currency: "CAD",
    sector: "Financials",
    executedPrice: 64.0,
    cadPriceAtExecution: 64.0,
    shares: 12.0,
    bookValue: 768.0,
  },
  {
    id: "15",
    name: "Celestica Inc.",
    symbol: "CLS.TO",
    currency: "CAD",
    sector: "Info Tech",
    executedPrice: 434.0,
    cadPriceAtExecution: 434.0,
    shares: 2.0,
    bookValue: 868.0,
  },
  {
    id: "16",
    name: "Shopify Inc. Class A",
    symbol: "SHOP.TO",
    currency: "CAD",
    sector: "Info Tech",
    executedPrice: 244.93,
    cadPriceAtExecution: 244.9,
    shares: 2.0,
    bookValue: 489.9,
  },
  {
    id: "17",
    name: "CGI Inc. Class A",
    symbol: "GIB-A.TO",
    currency: "CAD",
    sector: "Info Tech",
    executedPrice: 122.5,
    cadPriceAtExecution: 122.5,
    shares: 3.0,
    bookValue: 367.5,
  },
  {
    id: "18",
    name: "Intuit Inc.",
    symbol: "INTU",
    currency: "USD",
    sector: "Info Tech",
    executedPrice: 675.72,
    cadPriceAtExecution: 940.2,
    shares: 1.0,
    bookValue: 940.2,
  },
  {
    id: "19",
    name: "Rogers Communications",
    symbol: "RCI-B.TO",
    currency: "CAD",
    sector: "Communica",
    executedPrice: 51.9,
    cadPriceAtExecution: 51.9,
    shares: 12.0,
    bookValue: 622.8,
  },
  {
    id: "20",
    name: "Cash",
    symbol: "CASH",
    currency: "CAD",
    sector: "N/A",
    executedPrice: 1.0,
    cadPriceAtExecution: 1.0,
    shares: 1873.0,
    bookValue: 1873.0,
  },
];
